# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False, verbose_name=b'ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'event name')),
                ('details', models.TextField(blank=True, verbose_name=b'details')),
                ('place', models.CharField(blank=True, max_length=40, verbose_name=b'where')),
                ('date', models.DateField(blank=True, verbose_name=b'when')),
                ('votingStart', models.DateField(blank=True)),
                ('votingEnd', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVTDATE',
            fields=[
                ('evtdateid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MDATE',
            fields=[
                ('mdateid', models.AutoField(primary_key=True, serialize=False)),
                ('meetingDateTimeS', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name=b'ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'name')),
                ('login', models.CharField(max_length=20, verbose_name=b'nickname')),
                ('email', models.CharField(max_length=50, verbose_name=b'e-mail')),
                ('password', models.CharField(max_length=30, verbose_name=b'password')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name=b'city')),
            ],
        ),
        migrations.CreateModel(
            name='VOTE',
            fields=[
                ('voteid', models.AutoField(primary_key=True, serialize=False)),
                ('edate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EVTDATE')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.USER')),
            ],
        ),
        migrations.AddField(
            model_name='evtdate',
            name='dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MDATE'),
        ),
        migrations.AddField(
            model_name='evtdate',
            name='evt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EVENT'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='app.USER'),
        ),
    ]
