# -*- coding: utf-8 -*-
"""
Django settings for channels_chat project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ntkza9*338^lok9gumrsrz*!msb8usyhc+(flajhl0+yura^tl'

DEBUG = True

ALLOWED_HOSTS = ['192.168.2.149','192.168.131.152', '192.168.78.128','127.0.0.1']

#SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
#  'locale': 'ru_RU',
#  'fields': 'id, name, email',
#}
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'social_django',
   'social.apps.django_app.default',
    'chat',
#    'flickr',
    'users',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "channels_chat.routing.channel_routing",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # <--
 'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'channels_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--
            ],
        },
    },
]

WSGI_APPLICATION = 'channels_chat.wsgi.application'

AUTHENTICATION_BACKENDS = (
                           'social_core.backends.github.GithubOAuth2',
                           'social_core.backends.twitter.TwitterOAuth',
                           'social_core.backends.facebook.FacebookOAuth2',
                           'social_core.backends.open_id.OpenIdAuth',
                           'social_core.backends.google.GoogleOpenId',
                           'social_core.backends.google.GoogleOAuth2',
			'social_core.backends.linkedin.LinkedinOAuth2',
			'social_core.backends.google.GoogleOAuth',
		    'social_core.backends.dropbox.DropboxOAuth2',
		  'social_core.backends.instagram.InstagramOAuth2',

#			'social_core.backends.foursquare.FoursquareOAuth2'
#			'social_core.backends.vk.VKOAuth2'
#		            'social.backends.facebook.FacebookOAuth2',
#   			    'social.backends.google.GoogleOAuth2',
  			  'django.contrib.auth.backends.ModelBackend',
                           )
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
   # 'users.pipeline.get_avatar',
#	'users.pipeline.set_user_avatar',		
)
SOCIAL_AUTH_SLUGIFY_USERNAMES = True
SOCIAL_AUTH_CLEAN_USERNAMES = True
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']
# Чтобы запросить дополнительные поля, нужно указать их в EXTRA_DATA,
SOCIAL_AUTH_VK_OAUTH2_EXTRA_DATA = ['photo_200_orig']
SOCIAL_AUTH_VK_OAUTH2_API_VERSION = '5.5'
SOCIAL_AUTH_VK_APP_ID = '6055359'
SOCIAL_AUTH_VK_API_SECRET = 'Q8BOEYnzf51zDurCdcmg'
SOCIAL_AUTH_VK_OAUTH2_KEY = '6055359'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'Q8BOEYnzf51zDurCdcmg'
SOCIAL_AUTH_VK_OAUTH2_API_VERSION = 5.52
SOCIAL_AUTH_SANITIZE_REDIRECTS = True

SOCIAL_AUTH_VKONTAKTE_APP_SECRET =SOCIAL_AUTH_VK_API_SECRET
SOCIAL_AUTH_GITHUB_KEY = 'ff0644790ee1a63bc7a4'
SOCIAL_AUTH_GITHUB_SECRET = '7c6c93ac4db76cc76eeb6dee16c50c5f98205c1c'
SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.8'
#SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_TWITTER_KEY = '4w3nZcNO9XfyxACUm60cnrh6c'
SOCIAL_AUTH_TWITTER_SECRET = 'zJMkGZBY0aEApUyf8vJD2nTfkCkakLiutjHfs3Lp0t4zqoEbps'
SOCIAL_AUTH_GOOGLE_OAUTH2_CLIENT_ID  = '1071858907364-jdd3u3ukofl62lh9rd7vi9lp94qlnbt6.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_CLIENT_SECRET = 'o8KgvpYCs1naOjRAUJuWK-Z6'
SOCIAL_AUTH_FACEBOOK_KEY = '297898963990744'
SOCIAL_AUTH_FACEBOOK_SECRET = '2d4a0942a2abaa9b22b9d7583d31938b'
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY='86ycnxkkklyglk'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = '2DoS5EBhU3tobFte'
SOCIAL_AUTH_FOURSQUARE_KEY = 'TYSGK0VYAE3YIZWTS0A3P0QYLJC2KC0XIFDLUAZK4J10MG1V'
SOCIAL_AUTH_FOURSQUARE_SECRET = 'DLW0FVUHQ0SZEVN4J2WJ5LSR5RWXPUKQS4YTNDVHRNCZX4WG'

FLICKR_KEY='16749e9424a7a0d87a568f6fc38fb395'
FLICKR_SECRET='97b147a2ff6c10cf'
FLICKR_PERMISE='read'
CONNECTED_ACCOUNTS_INSTAGRAM_CONSUMER_KEY = '<instagram_client_id>'
CONNECTED_ACCOUNTS_INSTAGRAM_CONSUMER_SECRET = '<instagram_client_secret>'
SOCIAL_AUTH_DROPBOX_OAUTH2_KEY = 'yyrmbktug86ilcb'
SOCIAL_AUTH_DROPBOX_OAUTH2_SECRET = 'nvbr7d4ld4mt559'

SOCIAL_AUTH_INSTAGRAM_KEY = '8dcccdd5bc1f47f3af11c057423eb0ab'
SOCIAL_AUTH_INSTAGRAM_SECRET = 'a96b6c5861f94839b4b5bdd227e95a67'

SOCIAL_AUTH_INSTAGRAM_AUTH_EXTRA_ARGUMENTS = {'scope': 'likes comments relationships'}
SOCIAL_AUTH_GITHUB_SCOPE = ['repo']

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = 'users/login'

LOGIN_REDIRECT_URL = '/chat'
LOGIN_ERROR_URL = '/login/'
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = 'slaptazodis' #my gmail password
EMAIL_HOST_USER = 'infochatroom13@gmail.com' #my gmail username
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
