# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstbet', models.CharField(choices=[('st', 'stone'), ('sc', 'scissors'), ('p', 'paper'), ('l', 'lizard'), ('sp', 'spock')], default='', max_length=2)),
                ('secondbet', models.CharField(choices=[('st', 'stone'), ('sc', 'scissors'), ('p', 'paper'), ('l', 'lizard'), ('sp', 'spock')], default='', max_length=2)),
                ('game_status', models.CharField(choices=[('d', 'draw'), ('f', 'firstwon'), ('s', 'secondwon'), ('n', 'notplayed')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='firstuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to='ssplsapp.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='seconduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seconduser', to='ssplsapp.User'),
        ),
    ]
