# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssplsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
    ]
