# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssplsapp', '0003_auto_20170503_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='firstbet',
            field=models.CharField(choices=[('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spock', 'spock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='secondbet',
            field=models.CharField(choices=[('nb', ''), ('stone', 'stone'), ('scissors', 'scissors'), ('paper', 'paper'), ('lizard', 'lizard'), ('spock', 'spock')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('np', ''), ('firstwon', 'firstwon'), ('secondwon', 'secondwon'), ('draw', 'draw')], default='', max_length=10),
        ),
    ]
